### ISSUE TITLE
Add roles to Home page

### ISSUE THREAD

**Issue by nivedhanatarajan7** [DevDogs-UGA/DevDogs-Website#18]
![Image](https://github.com/user-attachments/assets/ddb60bdf-5681-46d5-942d-8247fb188f2f)

Cycle through roles text on homepage while the webpage is being viewed. See Figma for more info.

**Comment by jayp822** [comment]
Do I need to get permission to work on this issue, I am new to repo. Im a 4th year CS student at UGA.

**Comment by justinquinnb** [comment]
This issue is being reopened as it was not correctly described. Credit will still be given to the original contribution. Please see this issue's new description for more info.

**Comment by jayp822** [comment]
#54
