### ISSUE TITLE
Create Carousel Component

### ISSUE THREAD

**Issue by nivedhanatarajan7** [DevDogs-UGA/DevDogs-Website#24]
**Description:**  Create a carousel component that can be used in various pages.

**Resources**
Figma: https://www.figma.com/design/mJZGzkMqu6JHfIzPl5zCkU/Website-Design?node-id=15-117&t=oScVUwE20rTBxjWP-0

**Comment by DogeDevYT** [comment]
I made the component a while ago but I forgot  to comment the pr link

https://github.com/DevDogs-UGA/DevDogs-Website/pull/30
