### ISSUE TITLE
Create Our People Page

### ISSUE THREAD

**Issue by nivedhanatarajan7** [DevDogs-UGA/DevDogs-Website#27]
Description: Create Our People page, contains cards with members.

Resources
Figma: https://www.figma.com/design/mJZGzkMqu6JHfIzPl5zCkU/Website-Design?node-id=207-416&t=oScVUwE20rTBxjWP-0

**Comment by KelseySt** [comment]
Might take this on, but if not here's a resource for building a simple carousel to build off of since it will need a lot of customization.

https://dev.to/rakumairu/simple-react-carousel-24m0
