### ISSUE TITLE
Create Our Projects Page

### ISSUE THREAD

**Issue by nivedhanatarajan7** [DevDogs-UGA/DevDogs-Website#28]
**Description:** Create Our Projects page, with cards that link to pages about the projects

**Resources**
Figma: https://www.figma.com/design/mJZGzkMqu6JHfIzPl5zCkU/Website-Design?node-id=208-666&t=a2tqj7WLLBKzkn3Z-0

**Comment by jayp822** [comment]
I can start working on this

**Comment by jayp822** [comment]
#55
