### ISSUE TITLE
Inconsistent navbar text size across pages

### ISSUE THREAD

**Issue by justinquinnb** [DevDogs-UGA/DevDogs-Website#47]
The page links in the navbar change size across different pages. The expected functionality is for their size to remain the same as that of the homepage.

**Example of different sizes (not exclusive to home and events pages):**
Size of text when on homepage:
![Image](https://github.com/user-attachments/assets/9307d250-ee63-4336-9bb0-796dbd8584a8)

Size of text when on events page:
![Image](https://github.com/user-attachments/assets/0e76eb03-a87c-4925-96e8-52324661c581)

**Comment by nivedhanatarajan7** [comment]
The Navbar has been updated with dropdowns for related pages, and the sizing seems to be consistent between pages now. If you could confirm this as well, that would be great.

**Comment by justinquinnb** [comment]
Issue still present on Desktop

**Comment by jayp822** [comment]
#108
