### ISSUE TITLE
Update footer to match Figma

### ISSUE THREAD

**Issue by justinquinnb** [DevDogs-UGA/DevDogs-Website#48]
**Refer to the project's Figma page for the new look of the footer:**
![Image](https://github.com/user-attachments/assets/0de0b8fa-dea8-4e0f-a2af-c8d754101765)
Each social icon should link to the respective profile page. As seen in the screenshot and Figma, non-footer elements (circled in orange) should be able to overlap the footer's background image.

**As part of this issue, please eliminate the disproportionate stretching of the footer's background image, present on different pages:** 
![Image](https://github.com/user-attachments/assets/692aa708-7c07-4018-a1a7-3d5c5e8a182c)
The intended functionality is the footer to scale with its proportions maintained. As seen, the footer stretches and compresses instead.

**Comment by adogins** [comment]
I tried to fix the issue with the background in the footer, however it won't stretch outside of the boundaries of the footer.

**Comment by jayp822** [comment]
> I tried to fix the issue with the background in the footer, however it won't stretch outside of the boundaries of the footer.

#60
