### ISSUE TITLE
Navbar should be shorter

### ISSUE THREAD

**Issue by ggliv** [DevDogs-UGA/DevDogs-Website#66]
The current navbar is about twice as tall as it should be according to the Figma design. Figma says it should be about 8.7% of the height of a 1080p screen while master is currently at 18.2%.

| Current | Figma |
| - | - |
| ![Current](https://github.com/user-attachments/assets/bbadcbfc-6be3-4f7b-9326-7b8915490ddd) | ![Figma](https://github.com/user-attachments/assets/1591167c-ef05-4860-b121-ca6140252496) |

**Comment by ggliv** [comment]
I've actually got some free time, so I'll look at this myself.

**Comment by jayp822** [comment]
@ggliv sounds good it should be easy to do it in tailwind just mess around with some values, it is good practice to use rem though. To do any custom anything in tailwind just use propertyname-[value in whatever size] in the className.

**Comment by ggliv** [comment]
> @ggliv sounds good it should be easy to do it in tailwind just mess around with some values, it is good practice to use rem though. To do any custom anything in tailwind just use propertyname-[value in whatever size] in the className.

Yep, I've opened a PR to fix this issue. I opted to use `em` instead of `rem` for the navbar logo since it's meant to be roughly the same size as the text, though.

Feel free to drop a review on that PR if you want, by the way.
