### ISSUE TITLE
Fix incorrect text formatting

### ISSUE THREAD

**Issue by justinquinnb** [DevDogs-UGA/DevDogs-Website#82]
This issue is a doozy. It encompasses multiple, smaller details that need to be resolved for parity with the Figma and adherence to our brand's visual language. In resolving this issue, please be sure to:

- Change the color used in red, emphasized HERO/banner headers to #e4002b (Glory Glory Red)
    - Non-hero, emphasized header text should all remain #ba0c2f (Bulldog Red)
- Change the default color for HERO/banner headers to #222233 (Midnight Blue)
    - Non-hero header text should be changed to #33334d (DevDog Blue)
 - All body text should be Pure Black (#000000)
 - Line spacing in headers (especially visible on the homepage) should be decreased to match the Figma 
 - Home page text sizes and weights should be changed to better reflect the Figma and improve legibility
 - Website fonts should be updated across the board
     - ALL headers should use [Baru Sans](https://fontesk.com/baru-sans-typeface/) (or pull from another site) in the Extra Bold variety
     - All body text should use [Myriad Pro](https://fonts.adobe.com/fonts/myriad) (or pull from another site) in the Regular and Extra Bold variants
     - [Heebo](https://fonts.adobe.com/fonts/heebo) (bold and regular) can serve as a fallback for Baru Sans Extra Bold and Myriad Pro Regular/Bold

**Examples of the issues:**
![Image](https://github.com/user-attachments/assets/f6e6d08f-9a74-4678-a0e7-0c94e6b8a3b9)
![Image](https://github.com/user-attachments/assets/56889089-941a-4951-9b9f-b9542f7926b6)
![Image](https://github.com/user-attachments/assets/d1dabacd-2d7b-4488-8d00-1bf1bd6db42d)

**Example of the desired look:**
![Image](https://github.com/user-attachments/assets/0d0b6784-3a42-48fc-a3fb-8066a1be53ea)

**Comment by jayp822** [comment]
#86
